version: '3'

services:
  mariadb:
    container_name: weather_db
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weather
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql